name: Build and Push Docker Image To AWS ECR
on:
  workflow_dispatch:

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    # - run: docker buildx build -t app .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR Private
      id: login-ecr-private
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: private

    - name: Build, tag, and push docker image to Amazon ECR Private
      env:
        # REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        REGISTRY_ALIAS: ${{ secrets.ECR_URI }}
        # REPOSITORY: first-private-ecr
        IMAGE_TAG: latest
      run: |
        aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 061039771693.dkr.ecr.ap-northeast-2.amazonaws.com
        docker build -t $REGISTRY_ALIAS:$IMAGE_TAG .
        docker push $REGISTRY_ALIAS:$IMAGE_TAG
