name: SCP files From Actions To EC2
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: File made by Github Actions ubuntu
        run: touch actions-file.log
      
      - name: From Github Actions to AWS EC2 through SCP
        uses: appleboy/scp-action@v0.1.7
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: actions-file.log
          target: /home/ubuntu
      - name: From Github Actions to AWS EC2 through SCP
        uses: appleboy/scp-action@v0.1.7
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: app.jar
          target: /home/ubuntu/app
      - name: Connecting EC2 through SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
             rm -rf /home/ubuntu/app/deploy
             mkdir /home/ubuntu/app/deploy
             mv /home/ubuntu/app/app.jar /home/ubuntu/app/deploy/app.jar
             cd /home/ubuntu/app/deploy
             sudo fuser -k -n tcp 8080 || true
             nohup java -jar app.jar > ./output.log 2>&1 &
             rm -rf /home/ubuntu/app
