name: SCP files From Actions To EC2
on: workflow_dispatch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: File made by Github Actions ubuntu
        run: touch actions-file.log
